### ISSUE TITLE
https://github.com/franck-paul/dcRevisions/issues/new

### ISSUE THREAD

**Issue by gibus** [franck-paul/dcRevisions#1]
When creating a new post, either in wiki or xhtml when dcLegacyEditor is configured for this format, if dcRevisions is enabled a javascript exception is raised, stopping any further javascript processing and therefore fully breaking the creation form. This happens with Dotclear 2.18, dcRevisions 0.5, dcLegacyEditor 0.1.4.

The issue does not arise when dcRevisions is disabled.

Here's the exception and the error as captured by Firefox console:

    jQuery.Deferred exception: formatField is undefined @<blog_url>/admin/index.php?pf=dcLegacyEditor%2Fjs%2F_post_editor.js&v=2.18:8:50
    dispatch@<blog_url>/admin/js/jquery/jquery.js?v=2.18:325:403
    add/elemData.handle@<blog_url>/admin/js/jquery/jquery.js?v=2.18:311:144
    trigger@<blog_url>/admin/js/jquery/jquery.js?v=2.18:551:237
    trigger/<@<blog_url>/admin/js/jquery/jquery.js?v=2.18:557:245
    each@<blog_url>/admin/js/jquery/jquery.js?v=2.18:17:208
    each@<blog_url>/admin/js/jquery/jquery.js?v=2.18:8:185
    trigger@<blog_url>/admin/js/jquery/jquery.js?v=2.18:557:224
    $.pageTabs/<@<blog_url>/admin/js/jquery/jquery.pageTabs.js?v=2.18:3:416
    dispatch@<blog_url>/admin/js/jquery/jquery.js?v=2.18:325:403
    add/elemData.handle@<blog_url>/admin/js/jquery/jquery.js?v=2.18:311:144
    trigger@<blog_url>/admin/js/jquery/jquery.js?v=2.18:551:237
    trigger/<@<blog_url>/admin/js/jquery/jquery.js?v=2.18:557:245
    each@<blog_url>/admin/js/jquery/jquery.js?v=2.18:17:208
    each@<blog_url>/admin/js/jquery/jquery.js?v=2.18:8:185
    trigger@<blog_url>/admin/js/jquery/jquery.js?v=2.18:557:224
    $.pageTabs.clickTab@<blog_url>/admin/js/jquery/jquery.pageTabs.js?v=2.18:7:1
    $.pageTabs@<blog_url>/admin/js/jquery/jquery.pageTabs.js?v=2.18:4:143
    @<blog_url>/admin/js/page-tabs.js?v=2.18:1:64
    mightThrow@<blog_url>/admin/js/jquery/jquery.js?v=2.18:214:10
    resolve/</process<@<blog_url>/admin/js/jquery/jquery.js?v=2.18:216:89
     undefined
    jquery.js:225:231

    TypeError: formatField is undefined index.php:8:50
    <anonyme> <blog_url>/admin/index.php:8:50
    dispatch <blog_url>/admin/js/jquery/jquery.js:325:403
    add/elemData.handle <blog_url>/admin/js/jquery/jquery.js:311:144
    trigger <blog_url>/admin/js/jquery/jquery.js:551:237
    trigger/< <blog_url>/admin/js/jquery/jquery.js:557:245
    each <blog_url>/admin/js/jquery/jquery.js:17:208
    each <blog_url>/admin/js/jquery/jquery.js:8:185
    trigger <blog_url>/admin/js/jquery/jquery.js:557:224
    $.pageTabs/< <blog_url>/admin/js/jquery/jquery.pageTabs.js:3:416
    dispatch <blog_url>/admin/js/jquery/jquery.js:325:403
    add/elemData.handle <blog_url>/admin/js/jquery/jquery.js:311:144
    trigger <blog_url>/admin/js/jquery/jquery.js:551:237
    trigger/< <blog_url>/admin/js/jquery/jquery.js:557:245
    each <blog_url>/admin/js/jquery/jquery.js:17:208
    each <blog_url>/admin/js/jquery/jquery.js:8:185
    trigger <blog_url>/admin/js/jquery/jquery.js:557:224
    $.pageTabs.clickTab <blog_url>/admin/js/jquery/jquery.pageTabs.js:7:1
    $.pageTabs <blog_url>/admin/js/jquery/jquery.pageTabs.js:4:143
    <anonyme> <blog_url>/admin/js/page-tabs.js:1:64
    mightThrow <blog_url>/admin/js/jquery/jquery.js:214:10
    resolve/</process< <blog_url>/admin/js/jquery/jquery.js:216:89

**Comment by franck-paul** [comment]
Is there any adBlocker as uBlock, Ghostery or Privacy Badger enabled on the admin?

**Comment by gibus** [comment]
Yes but this was not relevant for this issue. Thanks for having merged the pull request. The issue is fixed
