### ISSUE TITLE
Historique qui se déplie à chaque enregistrement du billet

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/dcRevisions#5]
L'historique des révisions, s'il est refermé avant l'enregistrement se déplie systématiquement après chaque enregistrement de modification du billet.
dcRevisions v3.3 / dotclear 2.27.1

**Comment by franck-paul** [comment]
Ça devrait normalement être résolu avec la 2.27.2 (cf [https://git.dotclear.org/dev/dotclear/commit/7cc1d79abc33ad0aabd0b40240abdad7a741ff0e)](https://git.dotclear.org/dev/dotclear/commit/7cc1d79abc33ad0aabd0b40240abdad7a741ff0e))

À rouvrir si besoin une fois mis à jour et testé en 2.27.2
